version: 1.0.{build}
image: Visual Studio 2017
skip_tags: true
init:
- cmd: git config --global core.autocrlf true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- ps: >-
    dotnet --version

    dotnet publish -v m --configuration Release --force --self-contained --output .\Release-wsl-ssh-pageant\

    $env:Path += ";C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\Hostx64\x64"

    editbin /subsystem:windows .\Release-wsl-SSH-Pageant\wsl-ssh-pageant.exe

    7z a wsl-ssh-pageant-$env:APPVEYOR_BUILD_VERSION.zip .\Release-wsl-ssh-pageant\
test: off
artifacts:
- path: wsl-ssh-pageant*.zip
  name: Github Releases
deploy:
- provider: GitHub
  tag: appveyor-$(APPVEYOR_BUILD_VERSION)
  release: WSL-SSH-PAGEANT - Release $(APPVEYOR_BUILD_VERSION)
  description: 'Automated Build & Release.\nBuild Commit : $(APPVEYOR_REPO_COMMIT).\nBuild Version : $(APPVEYOR_BUILD_VERSION)'
  auth_token:
    secure: iwJ2Z1xRxHSDNDgORj/wGCJ14DZXhrO82BCVjRok23Oxd3XxHQrj7RhFAGaGuaCD
  prerelease: true
  force_update: true
  on:
    branch: master